[general]
import = ["~/.config/alacritty/current_theme.toml"]
live_config_reload = true

[font]
size = 16

[font.normal]
family = "MesloLGM Nerd Font"

[window]
opacity = 0.8

[window.dimensions]
lines = 35
columns = 140

[env]
TERM = "xterm-256color"
